Web/Controllers/ListController.cs
using System.Diagnostics;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Contracts.Database;
using Domain.Commands;
using Domain.Queries;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Primitives;
using Microsoft.IdentityModel.Tokens;
using Web.Models;
using Web.Services.Interfaces;

namespace Web.Controllers;

public class ListController : Controller
{
    private readonly IMediator _mediator;
    private readonly ITokenHandler _tokenHandler;
    private readonly ILogger<ListController> _logger;

    public ListController(IMediator mediator,
        ITokenHandler tokenHandler,
        ILogger<ListController> logger)
    {
        _mediator = mediator;
        _logger = logger;
        _tokenHandler = tokenHandler;
    }

    public async Task<IActionResult> ListTasks(int id, CancellationToken cancellationToken)
    {
        if (!IsAuthorized(out int _))
        {
            return RedirectToAction("SignIn", "Session");
        }

        GetToDoTasksByListIdQuery query = new() { ToDoListId = id };
        GetToDoTasksByListIdQueryResult result = await _mediator.Send(query, cancellationToken);

        return View(result.ToDoListTasksPage);
    }

    public async Task<IActionResult> MyLists(CancellationToken cancellationToken)
    {
        if (!IsAuthorized(out int userId))
        {
            return RedirectToAction("SignIn", "Session");
        }

        GetToDoListsByUserIdQuery query = new() { UserId = userId };
        GetToDoListsByUserIdQueryResult result = await _mediator.Send(query, cancellationToken);

        return View(result.ToDoLists);
    }

    public IActionResult CreateNewList()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreateNewList([FromForm] ToDoList toDoList, CancellationToken cancellationToken)
    {
        if (!IsAuthorized(out int userId))
        {
            return RedirectToAction("SignIn", "Session");
        }

        CreateToDoListCommand command = new()
        {
            UserId = userId,
            ToDoListName = toDoList.Name,
            ToDoListDescription = toDoList.Description
        };
        CreateToDoListCommandResult result = await _mediator.Send(command, cancellationToken);

        return Redirect("MyLists");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    private bool IsAuthorized(out int userId)
    {
        if (HttpContext.Request.Cookies.TryGetValue("jwt", out string token))
        {
            return _tokenHandler.Validate(token, out userId);
        }

        userId = -1;
        return false;
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="List" asp-action="MyLists">ToDo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="List" asp-action="MyLists">MyLists</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="List" asp-action="CreateNewList">New List</a>
                        </li>
                    </ul>

                    <hr class="toggle-menu-vertical-separator">
                    <span class="navbar-text" id="session-info">
                        @if(!string.IsNullOrEmpty(Context.Request.Cookies["jwt"]))
                        {                                
                            <a class="sign-out-link" id="sign-out-link" href="/Session/Signout">Sign out</a>
                        }
                        else
                        {
                            <a class="sign-in-link" id="sign-out-link" href="/Session/Signin">Sign In</a>                                
                        }
                    </span>          
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>